//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyProjectDBEntities : DbContext
    {
        public MyProjectDBEntities()
            : base("name=MyProjectDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Notice_info> Notice_info { get; set; }
        public virtual DbSet<User_info> User_info { get; set; }
        public virtual DbSet<Video_info> Video_info { get; set; }
        public virtual DbSet<Video_Inspect> Video_Inspect { get; set; }
        public virtual DbSet<Video_Vote> Video_Vote { get; set; }
        public virtual DbSet<WebSet_Tip> WebSet_Tip { get; set; }
    }
}
