//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video_info
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Synopsis { get; set; }
        public string UpDate { get; set; }
        public string VideoContent { get; set; }
        public string AV_Number { get; set; }
        public string OccurrenceTime { get; set; }
        public string Address { get; set; }
        public Nullable<bool> AuditStatus { get; set; }
        public Nullable<bool> AuditResultStatus { get; set; }
        public Nullable<bool> VideoStatus { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<int> Reading { get; set; }
    }
}
